# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-variantcallerbench-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # TODO nf-core: Add required software dependencies here
  - fastqc=0.11.8
  - multiqc=1.7
  - samtools=1.9
  - seqkit=0.9.2
  - spades=3.12.0
  - trimmomatic=0.38
  - bowtie2=2.3.4.3
  - biopython=1.72
